### ISSUE TITLE
「作業中断」「作業再開」で休憩時間をノート欄に記録する

### ISSUE THREAD

**Issue by sndtkrh** [sensetime-jp/miyamoto#11]
# 概要
「作業中断」「作業再開」等で休憩時間をスプレッドシートのノート欄に記録したい

# 要件
- 「作業中断」「作業再開」に反応し中断時刻、再開時刻をノートに記録すること

# タスク
- [x] コードの変更
- [x] スクリーンショット取得
- [x] レビュー
- [x] デプロイ

**Comment by nayutaya** [comment]
@sndtkrh 「タスク」への状態の反映をお願いします。

**Comment by stayalexey** [comment]
デプロイが完了しているのを確認したので、クローズとする
