### ISSUE TITLE
頭文字の記号なしで反応するようにする

### ISSUE THREAD

**Issue by stayalexey** [sensetime-jp/miyamoto#13]
# 概要
現在、「`:man-walking:` 本日hh時mm分に退社します」といった予告に反応するようになっている。
これを変更し「`:man-walking:`」等なしで投稿した際に反応するようにしたい。

# 要件
- 出社・退社、作業中断、作業再開時に「`:man-walking:`」「`:woman-walking:`」「`:walking:`」等なしで打刻が可能
- 出社・退社、作業中断、作業再開時に「`:man-walking:`」「`:woman-walking:`」「`:walking:`」等含まれていてもで打刻が可能

# タスク
- [x] 変更方法の検討
- [x] コードの修正
- [x] スクリーンショットの取得
- [x] レビュー
- [x] デプロイ

**Comment by nayutaya** [comment]
@stayalexey 「要件」に「`:walkman:`が含まれていても、従来通りに反応すること」があると良いかもしれません。

**Comment by stayalexey** [comment]
@nayutaya 変更しました。さっそくありがとうございます。

**Comment by TogawaYoshihito** [comment]
重箱の隅ですが、正確には `man-walking` `woman-walking` のようですね。
![image](https://user-images.githubusercontent.com/29860111/52833759-d8a6c280-3121-11e9-96cf-4d5e87a40f81.png)

**Comment by stayalexey** [comment]
@TogawaYoshihito さっそくチェックありがとうございます。変更しておきました。

**Comment by stayalexey** [comment]
絵文字がついていても、いなくても反応している様子
![capture](https://user-images.githubusercontent.com/36610811/52938017-eec3b580-33a3-11e9-9b9f-31d6c359d87a.JPG)

**Comment by nayutaya** [comment]
@stayalexey Issueは様々な理由（作業の完了、キャンセルなど）でクローズされるので、クローズする際には理由を明示しておくと良いです。
