### ISSUE TITLE
「退社します」に反応しない不具合を修正する

### ISSUE THREAD

**Issue by sndtkrh** [sensetime-jp/miyamoto#7]
# 概要
現在「出社しました」には反応するが「退社します」には反応しない状態になっている。
このバグを修正する。

# 要件
- 「退社します」などの SignIn アクションに正常に反応する状態になること

# タスク
- [x] バグの原因を特定する
- [x] コードを修正する
- [x] デプロイする

**Comment by nayutaya** [comment]
@sndtkrh とても分かりやすいIssue、PRをありがとうございます。レビューしてPR #8 をマージしました。

ちなみにタスクリストには「デプロイする」まで含まれていると良いと思います。実際に動いている環境に反映されるところまでが不具合の修正作業です。

**Comment by sndtkrh** [comment]
デプロイされましたのでクローズします
