### ISSUE TITLE
出社・退社の予告等に反応しないようにする

### ISSUE THREAD

**Issue by sndtkrh** [sensetime-jp/miyamoto#9]
# 概要
現在、「本日hh時mm分に退社します」といった予告にも反応するようになっている。
これを変更し、実際の出社・退社時に「出社/退社します」と投稿したときのみに反応するようにしたい。

# 要件
- 出社・退社の予告等に反応せず、実際の出社・退社投稿にのみ反応すること

# タスク
- [x] 変更方法の検討
- [x] コードの修正
- [x] スクリーンショットの取得
- [x] レビュー
- [x] デプロイ

**Comment by sndtkrh** [comment]
退社予告に反応している様子
![screenshot from 2018-06-22 11-02-49](https://user-images.githubusercontent.com/5213322/41754128-083d32da-760c-11e8-9d93-5d13f39a267e.png)

**Comment by stayalexey** [comment]
デプロイが完了しているのを確認したので、クローズとする。
